#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;

$app = new App(require 'config.php');
$app->setSignature('./streamwidgets help');

$app->runCommand($argv);
