#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use StreamWidgets\Chatbot\ChatbotService;

$app = new App(require 'config.php');

$chatbot = new ChatbotService();
$chatbot->load($app);

$app->addService('chatbot', $chatbot);

$app->setSignature('./streamwidgets help');

$app->runCommand($argv);